MVCCrud&Partial view/MVCCrud/MVCCrud/Controllers/CrudController.cs
using MVCCrud.Data;
using MVCCrud.Models;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration;

namespace MVCCrud.Controllers
{
    public class CrudController : Controller
    {
        private readonly GeneralDbContext _generalContext;

        public CrudController(GeneralDbContext generalContext)
        {
            _generalContext = generalContext;
        }

        public IActionResult DetailsEmpData(string EmpId)
        {
            EmployeeInfo eObj = new EmployeeInfo();
            try
            {
                if(EmpId != null){
                    eObj = _generalContext.EmployeeInfo.FromSqlRaw("Select EmpId, EmpName, EmpAge, EmpPhNo, EmpSalary from EmployeeInfo where EmpId = {0}", EmpId).FirstOrDefault();
                }
            }catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return View(eObj);
        }


        // Without Primary Key
        public IActionResult EmpGetData()
        {
            return View();
        }

        public IActionResult StoreEmpData(EmployeeInfo details)
        {
            try
            {
                if (details != null)
                {
                    _generalContext.Database.ExecuteSqlRaw("Insert into EmployeeInfo(EmpId, EmpName, EmpAge, EmpPhNo, EmpSalary) values ({0}, {1}, {2}, {3}, {4});", details.EmpId, details.EmpName, details.EmpAge, details.EmpPhNo, details.EmpSalary);
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return RedirectToAction("EmpDisplayData");
            
        }

        public IActionResult EditEmployeeData(string EmpId) // `EmpId` parameter name is came from 'EmpDisplayData.cshtml => asp-route-EmpId`. So `asp-route name` and `parameter` must be same name.
        {
            EmployeeInfo empObj = new EmployeeInfo();
            try
            {
                if (EmpId != null)
                {
                    empObj = _generalContext.EmployeeInfo.FromSqlRaw("Select EmpId, EmpName, EmpAge, EmpPhNo, EmpSalary from EmployeeInfo where EmpId = {0}", EmpId).FirstOrDefault();

                }
            }
            catch(Exception e) {
                Console.WriteLine(e.Message);
            }
            return View(empObj);
        }

        public IActionResult UpdateEmployeeData(EmployeeInfo generalObj) //`EmployeeInfo` class must be used bcoz this class is came from the view of the `EditEmployeeData.cshtml`.
        {
            try
            {
                if(generalObj != null)
                {
                    _generalContext.Database.ExecuteSqlRaw("Update EmployeeInfo set EmpName={0}, EmpAge={1}, EmpPhNo={2}, EmpSalary={3} where EmpId={4}", generalObj.EmpName, generalObj.EmpAge, generalObj.EmpPhNo, generalObj.EmpSalary, generalObj.EmpId);
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return RedirectToAction("EmpDisplayData");
        }

        public IActionResult DeleteEmployeeData(string EmpId)
        {
            try
            {
                if (EmpId != null)
                {
                    _generalContext.Database.ExecuteSqlRaw("delete from EmployeeInfo where EmpId={0}", EmpId);
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return RedirectToAction("EmpDisplayData");
        }

        public IActionResult EmpDisplayData()
        {
            List<EmployeeInfo> employeeObj = new List<EmployeeInfo>();
            employeeObj = _generalContext.EmployeeInfo.FromSqlRaw("Select EmpId, EmpName, EmpAge, EmpPhNo, EmpSalary from EmployeeInfo").ToList();
            return View(employeeObj);
        }


        // With Primary key which is created in the database and set with auto increment values
        public IActionResult ProductsDisplayData()
        {
            List<ProductsInfo> productsObj = new List<ProductsInfo>();
            productsObj = _generalContext.ProductsInfo.FromSqlRaw("Select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo").ToList();
            return View(productsObj);
        }

        public IActionResult GetProductsData()
        {
            return View();
        }

        public IActionResult AddNewProducts(CommonModelClass generalObj)
        {
            try
            {
                if(generalObj != null)
                {
                    _generalContext.Database.ExecuteSqlRaw("Insert into ProductsInfo (ProdName, ProdQuantity, ProdPrice) values ({0}, {1}, {2})",generalObj.prodObj.ProdName, generalObj.prodObj.ProdQuantity, generalObj.prodObj.ProdPrice);
                }
            }
            catch(Exception e)
            {
                Console.Write(e.Message);
            }
            return RedirectToAction("ProductsDisplayData");
        }

        public IActionResult EditProductsInfo(int ProdId)
        {
            ProductsInfo proObj = new ProductsInfo();
            try
            {
                if (ProdId != null)
                {
                    proObj = _generalContext.ProductsInfo.FromSqlRaw("Select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo where ProdId={0}", ProdId).FirstOrDefault();
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return View(proObj);
        }

        public IActionResult UpdateProductsInfo(ProductsInfo productObj)
        {
            try
            {
                if (productObj != null)
                {
                    _generalContext.Database.ExecuteSqlRaw("Update ProductsInfo set ProdName={0}, ProdQuantity={1}, ProdPrice={2} where ProdId={3}", productObj.ProdName, productObj.ProdQuantity, productObj.ProdPrice, productObj.ProdId);
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return RedirectToAction("ProductsDisplayData");
        }

        public IActionResult DeleteProductsInfo(int ProdId)
        {
            try
            {
                if (ProdId != null)
                {
                    _generalContext.Database.ExecuteSqlRaw("delete from ProductsInfo where ProdId={0}", ProdId);
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return RedirectToAction("ProductsDisplayData");
        }

        public IActionResult DetailProductsInfo(int ProdId)
        {
            ProductsInfo pObj = new ProductsInfo();
            try
            {
                if (ProdId != null)
                {
                    pObj = _generalContext.ProductsInfo.FromSqlRaw("Select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo where ProdId={0}", ProdId).FirstOrDefault();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return View(pObj);
        }


    }
}

MVCCrud&Partial view/MVCCrud/MVCCrud/Controllers/PartialviewController.cs
using MVCCrud.Data;
using MVCCrud.Models;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace MVCCrud.Controllers
{
    public class PartialviewController : Controller
    {
        // We have to create this separate dbcontext for each controller
        private readonly GeneralDbContext _partialContext;

        // We have to create this separate dbcontext for each controller
        public PartialviewController(GeneralDbContext partialContext)
        {
            _partialContext = partialContext;
        }

        public IActionResult PartialViewMaster()
        {
            CommonModelClass proObj = new CommonModelClass(); // Creating object for `CommonModelClass` to access all the classess/tables 
            proObj.prodListObj = _partialContext.ProductsInfo.FromSqlRaw("Select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo").ToList();
            // `proObj.prodListObj` where `proObj` is an object created newly and `prodListObj` is an list object which is already created as a field in `CommonModelClass`.
            return View(proObj); // This object contains the full list of `ProductsInfo` table.
        }

        [HttpPost] // This name is used because the below action method is called/triggered from the AJAX request. For AJAX calling `[HttpPost]` is required bcoz after that it can send data to the database without loading the whole page. In the AJAX request we used `type:"POST"`
        public IActionResult AddNewProductsData([FromBody]ProductsInfo productObj)
        // `[FromBody]ProductsInfo productObj` where `[FromBody]` is an syntax for AJAX calling,
        // `ProductsInfo` is an table we already created, although we used `CommonModelClass` in the `_ProdCreateForm.cshtml` we were get the data through ajax(JSON.stringify), so we used the `ProductsInfo` class directly.
        // `productObj` is an object created newly to receive the data from ajax calling.
        {
            try
            {
                if (productObj != null)
                {
                    _partialContext.Database.ExecuteSqlRaw("Insert into ProductsInfo (ProdName, ProdQuantity, ProdPrice) values ({0}, {1}, {2})",productObj.ProdName, productObj.ProdQuantity, productObj.ProdPrice);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            CommonModelClass generalObj = new CommonModelClass();
            generalObj.prodListObj = _partialContext.ProductsInfo.FromSqlRaw("select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo").ToList();
            return PartialView("_ProdListTable", generalObj); 
            // `_ProdListTable` is the place/file where the object `generalObj` which contains all the list of data (of ProductsInfo talbe) will be going to fix.
            // While we use AJAX, we use `return PartialView("<.cshtml file name>",<object name>)` instead of  `return View(<object name>)`.
        }

        public IActionResult EditProductData(int ProdId) // Here we are not used `[HttpPost]` bcoz although it is an ajax calling action method, it is not going to send the data to the database. It will retrieve data from the databse because in the AJAX request we used `type:"GET"`.
        //`ProdId` name used in the both AJAX and field of `ProductsInfo` class.
        {
            ProductsInfo pObj = new ProductsInfo();
            try
            {
                if (ProdId != 0)
                {
                    pObj = _partialContext.ProductsInfo.FromSqlRaw("select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo where ProdId={0}", ProdId).FirstOrDefault();
                    var productDetails = new CommonModelClass { prodObj = pObj }; // This another type of passing the data
                    //`productDetails` is an object created for `CommonModelClass` where `prodObj` is already a field created in that Model class ad we assign the `pObj` object to that `prodObj` field which already indicates `ProductsInfo` class.

                    return PartialView("_ProdEditForm", productDetails);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            };
            return PartialView("_ProdEditForm", new ProductsInfo());
        }
        // new changes 2

        [HttpPost]
        public IActionResult UpdateProductData([FromBody]ProductsInfo pObj)
        {
            try
            {
                if (pObj != null) {
                    _partialContext.Database.ExecuteSqlRaw("update ProductsInfo set ProdName={0}, ProdQuantity={1}, ProdPrice={2} where ProdId={3}", pObj.ProdName, pObj.ProdQuantity, pObj.ProdPrice, pObj.ProdId);
                }
                else
                {
                    return Json("Failed"); // It return to the AJAX `error: function()`
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            CommonModelClass generalObj = new CommonModelClass();
            generalObj.prodListObj = _partialContext.ProductsInfo.FromSqlRaw("select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo").ToList();
            return PartialView("_ProdListTable", generalObj);
        }

        [HttpPost]
        public IActionResult DeleteProductData(int ProdId)
        {
            Console.WriteLine(ProdId);
            try
            {
                if (ProdId != 0)
                {
                    _partialContext.Database.ExecuteSqlRaw("delete from ProductsInfo where ProdId={0}", ProdId);
                }
                else
                {
                    return Json("Failed");
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            CommonModelClass generalObj = new CommonModelClass();
            generalObj.prodListObj = _partialContext.ProductsInfo.FromSqlRaw("select ProdId, ProdName, ProdQuantity, ProdPrice from ProductsInfo").ToList();
            return PartialView("_ProdListTable", generalObj);
        }
    }
}

MVCCrud&Partial view/MVCCrud/MVCCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCCrud.styles.css" asp-append-version="true" />
    <!-- Jquery and AJAX CDN --> <!-- We can also give this CDN in the `PartialViewMaster.cshtml`, here I have used this `_Layout.cshtml` layout to entire web page so I gave in this file-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crud" asp-action="EmpDisplayData">Employee(Without Primary Key in database)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crud" asp-action="ProductsDisplayData">Products(With Primary Key in database)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Partialview" asp-action="PartialViewMaster">Partial View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCCrud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>